### ISSUE TITLE
Not working with Ruby 2.2.2?

### ISSUE THREAD

**Issue by mbrookes** [savanna-initiative/savanna-outliers#4]
lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- descriptive_statistics/safe (LoadError)

**Comment by mac-r** [comment]
@mbrookes  this lib is a bit outdated, you are welcome to making a pull request :)

**Comment by mbrookes** [comment]
But that I could understand the code! :) 

I found a working implementation here: https://github.com/cpetersen/basic-stats

**Comment by sunilkumarnagoore** [comment]
gem install descriptive_statistics
and load it in your ruby file like
 require ' descriptive_statistics'
